name: Cypress component tests
on:
  push: { branches: ["**"] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm install
      - name: Test (Vitest)
        run: npm run test
  component:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm install
      - name: Run Cypress - Component Tests
        run: npm run ct:run
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm install
      - name: Install PHP Dependencies
        run: composer install
      - name: Migrate Database
        run: php artisan migrate --env=testing
      - name: Run Application Server
        run: npm run dev
      - name: Start Client for E2E Tests
        run: php artisan serve --port=8000
      - name: Run Cypress - E2E Tests
        run: npm run e2e:run
